import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

// Required to recreate __dirname in ES modules (since it's not available by default)
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// FlatCompat allows use of legacy ESLint configs (like Next.js presets)
// within the newer "flat config" system
const compat = new FlatCompat({
  baseDirectory: __dirname,
});

// Main ESLint configuration for the project
// Extends Next.js recommended rules for performance and TypeScript safety
const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // Ignore generated/build files that should not be linted
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts", // auto-generated by Next.js
    ],
  },
];

export default eslintConfig;